FROM python

RUN pip install poetry

WORKDIR /code

COPY pyproject.toml .

RUN poetry config virtualenvs.create false \
    && poetry install 

COPY . .

EXPOSE 8000

CMD ["fastapi", "run", "main.py"]