"""refactor database

Revision ID: 30137ed53ed8
Revises: 5ba91d0b9bea
Create Date: 2024-06-24 01:54:06.818357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30137ed53ed8'
down_revision: Union[str, None] = '5ba91d0b9bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('custom_codes')
    op.drop_table('premium_links')
    op.drop_table('users')
    op.drop_table('free_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_urls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original_url', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('id_premium_link', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_premium_link'], ['premium_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('premium_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('custom_domain', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain')
    )
    op.create_table('custom_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original_url', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('id_premium_link', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_premium_link'], ['premium_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('original_url')
    )
    op.drop_table('code')
    op.drop_table('user')
    # ### end Alembic commands ###
