"""delete column last name user table

Revision ID: 74d861444a23
Revises: 8176005e4410
Create Date: 2024-06-06 00:10:53.199429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d861444a23'
down_revision: Union[str, None] = '8176005e4410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
