"""add optional the foregin key at start

Revision ID: aae0b34c4ab6
Revises: 6cbf964cf44a
Create Date: 2024-06-09 01:53:19.264060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae0b34c4ab6'
down_revision: Union[str, None] = '6cbf964cf44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_premium_link',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_premium_link',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
